name: Validate xref

on:
  pull_request:
    paths:
      - 'modules/**'
      - 'antora.yml'
      - '.github/workflows/pr-validate-references.yml'

jobs:
  validate_xref:
    uses: bonitasoft/bonita-documentation-site/.github/workflows/_reusable_pr-validate-references.yml@feat/create_uib_documentation
    secrets: inherit
    with:
      component-name: ui-builder
      doc-site-branch: 'feat/create_uib_documentation'
      fail-on-warning: true
